# Application Configuration
app:
  name: "Structural Health Monitoring"
  version: "1.0.0"
  environment: "development"  # development, staging, production
  debug: true

# API Settings
api:
  host: "0.0.0.0"
  port: 8000
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8000"
  api_prefix: "/api/v1"
  upload_dir: "uploads/api_uploads"
  max_upload_size: 10485760  # 10MB
  allowed_extensions: [".jpg", ".jpeg", ".png"]

# Model Configuration
model:
  name: "cnn"  # Options: cnn, resnet18, efficientnet
  num_classes: 2
  class_names: ["negative", "positive"]
  input_size: [224, 224]
  pretrained: true
  dropout: 0.5

# Training Configuration
training:
  batch_size: 32
  num_epochs: 50
  learning_rate: 0.001
  weight_decay: 0.0001
  early_stopping_patience: 10
  learning_rate_scheduler:
    factor: 0.1
    patience: 5
    min_lr: 0.00001

# Data Configuration
data:
  train_val_test_split: [0.7, 0.15, 0.15]
  augmentation:
    enabled: true
    rotation_range: 20
    width_shift_range: 0.2
    height_shift_range: 0.2
    horizontal_flip: true
    vertical_flip: true
    brightness_range: [0.8, 1.2]
    contrast_range: [0.8, 1.2]

# Database Configuration
database:
  url: "postgresql://user:password@localhost:5432/structmon"
  pool_size: 5
  max_overflow: 10

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/app.log"

# Storage Configuration
storage:
  type: "local"  # local, s3
  local:
    upload_dir: "uploads"
    results_dir: "results"
  s3:
    bucket_name: "structmon-data"
    region: "us-east-1"

# Monitoring and Analytics
monitoring:
  enabled: true
  metrics_port: 9090
  prometheus_endpoint: "/metrics"

# Security Settings
security:
  jwt_secret: "your-secret-key"  # Change in production
  jwt_algorithm: "HS256"
  token_expire_minutes: 60
  password_min_length: 8

# Image Processing
image_processing:
  supported_formats:
    - ".jpg"
    - ".jpeg"
    - ".png"
  max_file_size_mb: 10
  preprocessing:
    normalize: true
    augmentation: false

# Paths
paths:
  data_dir: "data"
  raw_data_dir: "data/raw"
  processed_data_dir: "data/processed"
  checkpoints_dir: "checkpoints"
  logs_dir: "logs"

# WebSocket Configuration
websocket:
  ping_interval: 20
  ping_timeout: 20
  close_timeout: 20
  max_message_size: 1048576  # 1MB 